# Generated by Django 3.2.8 on 2021-10-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя блока')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('height', models.IntegerField(verbose_name='высота')),
                ('width', models.IntegerField(verbose_name='ширина')),
                ('order_number', models.IntegerField(verbose_name='порядковый номер')),
                ('data', models.TextField(blank=True, verbose_name='данные')),
                ('type', models.SmallIntegerField(blank=True, verbose_name='тип')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.block')),
            ],
        ),
    ]
